### PR TITLE
Log tools

### PR DESCRIPTION
**Pull request by citlaligm**
The purpose of this PR is to provide logging tools for users. The `mono_logger.vi` allows the user to log data from from sensors. In a similar way the `mono_parse_binaries.vi` provides an example of how to parse the binary files.

A tutorial for how to use these tools will be published in readthedocs on this [PR ](https://github.com/monoDriveIO/documentation/pull/185)

logger

### CODE REVIEW

**Review by bradleynull — CHANGES_REQUESTED** [review]
@citlaligm This is a great tool! I was able to hook it up and use it, but I needed to insert the path to binary file as input to the `mono_logger.vi`. This wasn't specified in the image in the PR. A couple of comments;

1. Is it possible to log multiple sensors simultaneously? Do we need to make a copy of the VI to do that?
2. On the binary parser, can we automatically detect the sensor type? Using the drop down can still be there, but I was confused on why it didn't error when I was parsing camera data as GPS (the default drop down selection)
3. Can the output data start at 0 instead of 1? This would adhere to the KITTI format.

Overall things seem to be working for me. I'm unreasonably excited about getting to use this tool for R2V development!

**Comment by citlaligm** [comment]
@bradleynull thanks for your review. 

1.Yes, it is possible to add more of the logger.vi to the application, just copy-paste (Ctrl+C, Ctrl+V) the same VI, no need for creating another instance.

image

2. I think it is a good idea. I added the type of sensor to the name assigned by the user. Then on the parser, I detect the type of sensor from the name. Let me know your thoughts.

3. Done. Good catch! 


I think it is ready for another look. Thanks!

**Review by bradleynull — CHANGES_REQUESTED** [review]
@citlaligm Looks good for camera, but the LiDAR parsing seems to be failing when automatically detecting the sensor type: 

image

**Comment by citlaligm** [comment]
@bradleynull sorry about that. I actually think there is a bug on LV hehe, but I should have tested the other cases. I change the function I was using, and it looks correct now. It should be ready for another look.

**Review by bradleynull — APPROVED** [review]
@citlaligm Looks good to go. Approved!

**Pull request merged**
